### PR TITLE
Update addPairing to use Standings objects

### LINKED ISSUE #141: AddPairing and AddBye are inconsistent with what they take as arguments
**Is your feature request related to a problem? Please describe.**
The current addPairing function ask for players' name

**Describe the solution you'd like**
Change the addPairing function to ask for the Standings objects

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by stash86**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Update addPairing to use Standings objects

* **What is the current behavior?** (You can also link to an open issue here)
#141 

* **What is the new behavior (if this is a feature change)?**
addPairing function now requires Standings objects

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
You will need to make sure you are sending Standings object to addPairing. I have change all codes that are using it in current version.

* **Closing issues**
Closes #141

### CODE REVIEW

**Review by silasary — COMMENTED** [review]
This does not seem like a beneficial change

**Comment by stash86** [comment]
In blossom pairing code and my EventTests codes, I would have players' name only for the pairings. And I don't want to create a new Player object just to throw it to award_bye, where that function only gonna use player's name from that object anyway. Unless there is a specific reason why we want to maintain sending Player object to the function instead of just the name? For addPairing, we only send the names to the function. So I see no reason why award_bye can't be treated the same.

It's a cosmetic change in a way, but I feel like the proposed change gonna make it simpler and easier

**Comment by silasary** [comment]
Honestly, if we were to make things consistent, I'd rather it go the other way, and make AddPairing take a Player model.
There are some runtime checks I've been wanting to put in that depend on that change being made, so I feel like I'd end up having to revert these changes when I do that anyway.

**Comment by stash86** [comment]
As long as it's consistent, I'm fine with either one. I can change the addPairing now while I'm still tinkering on Event model

**Comment by stash86** [comment]
Right now award_bye is asking for Standings object, instead of (what I previously thought) Player object. Do you want to use Standings or Player object for the addPairing?

**Comment by silasary** [comment]
Standings is correct, yes.

**Comment by stash86** [comment]
Done. addPairing now use Standings model. Next I would need to update addMatch as well

**Pull request merged**
