### PR TITLE
Do not automatically attempt to resolve the round when editing an inactive event.

### LINKED ISSUE #139: Do not automatically attempt to resolve the round when editing an inactive event.

### PR DESCRIPTION
**Pull request by stash86**
After resolving a round, only pair the next round if the event is active.

I need this change for my test suites. I'm bulding several test events based on past events, and I don't want the pairing to be automated while the event is inactive. Only after I set the event as active, then the code can do the pairing automatically. And I assume some TO would need this feature as well in cases where they need to fix result from past events.

Fixes #139

### CODE REVIEW

**Comment by silasary** [comment]
I don't actually understand what this achieves.  Inserting matches while the event is inactive doesn't call resolveRound.

image

**Comment by stash86** [comment]
It indeed calls resolveRound function. I tried the old code, and it did give me pairing for round 2 although the event wasn't active

**Comment by silasary** [comment]
Ok.  Give this a better name and I'll merge it in.

**Comment by stash86** [comment]
I forgot to add that I added and reported the matches programmatically, not through host CP

**Pull request merged**
