### PR TITLE
Add more regex filters to normalize cards' name

### PR DESCRIPTION
**Pull request by stash86**
Add more regex filters since the current filter definitely not enough. I have few troubles importing PD legal list

### CODE REVIEW

**Comment by stash86** [comment]
Any way for me to edit the file without making new PR?

**Comment by silasary** [comment]
Continue editing your branch.  It'll update the PR

**Comment by stash86** [comment]
Any clue on what is wrong now? I need extra space on each line?

**Comment by silasary** [comment]
Eh, style-ci will automatically fix it if I merge.

**Pull request merged**
